development:
  access_key_id: "AKIAJDT7QLBNBTMDHJBA"
  secret_access_key: "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"
test:
  access_key_id: "AKIAJDT7QLBNBTMDHJBA"
  secret_access_key: "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"
production:
  access_key_id: "AKIAJDT7QLBNBTMDHJBA"
  secret_access_key: "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"
#TODO add correct security credentials